-- CREATE EXTENSION IF NOT EXISTS intarray;

CREATE EXTENSION IF NOT EXISTS postgis;

-- CREATE EXTENSION IF NOT EXISTS postgis_raster;

CREATE EXTENSION IF NOT EXISTS h3 CASCADE;

CREATE EXTENSION IF NOT EXISTS h3_postgis CASCADE;

-- CREATE EXTENSION IF NOT EXISTS hstore;
